name: ld-r deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "odp-reactor-ldr" #Must be unique in Heroku
          heroku_email: "odpreactor00@protonmail.com"
          branch: "develop"
        env:
          NODE_ENV: production
          HD_CONFIG_SPARQL_ENDPOINT_URI: https://arco.istc.cnr.it/odpr/sparql
          HD_CONFIG_SPARQL_ENDPOINT_HOST: arco.istc.cnr.it
          HD_CONFIG_SPARQL_ENDPOINT_PATH: /odpr/sparql
          HD_CONFIG_SPARQL_ENDPOINT_PORT: 443
          HD_CONFIG_SPARQL_ENDPOINT_TYPE: virtuoso
          HD_CONFIG_SPARQL_ENDPOINT_PROTOCOL: https
          HD_CONFIG_GRAPH: http://odpreactor.arco.istc.cnr.it/configuration
          HD_ODP_REACTOR_GRAPH_HOST: https://odp-reactor-browser.vercel.app
          HD_ODP_REACTOR_GRAPH_PORT: 443
          HD_TEST_SPARQL_ENDPOINT_URI: https://arco.istc.cnr.it/odpr/sparql
          HD_HOST: https://odp-reactor-ldr.herokuapp.com/
          PORT: 443
          HD_ALLOWED_ORIGINS: https://odp-reactor-ldr.herokuapp.com,https://odp-reactor-browser.vercel.app
          ALLOWED_ORIGINS: https://odp-reactor-ldr.herokuapp.com,https://odp-reactor-browser.vercel.app

